assets:
  - wordpress.sql.gz
steps:
  - name: Test Build now!
    plugin: WordPressApp
    subDirectory: 'www'
    database: wordpress.sql.gz
    databaseGzipped: true
    updatePlugins: true
    databaseName: woodpress
